# Generated by Django 4.2.1 on 2023-06-08 02:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoría de perfiles',
                'verbose_name_plural': 'categorías de perfiles',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
                ('realidad', models.CharField(max_length=50)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='descripción')),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de actualización')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.perfilcategoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
    ]
