# Generated by Django 4.2.1 on 2023-06-15 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripción')),
                ('imagen', models.URLField(null=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'misión',
                'verbose_name_plural': 'misiones',
            },
        ),
    ]
